name: Build Developer Guide

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Dev docs
    defaults:
      run:
        shell: bash
        working-directory: docs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install Graphviz
        run: sudo apt install graphviz
      - run: npm ci
      - run: npm run build
      - name: Check build status
        run: |
          if [ ! -d "./_site" ]; then
            echo "Build Error"
            exit 1
          fi
      - name: Deploy on push
        # if: ${{ success() && github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy
