name: Build Developer Guide

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    name: Dev docs
    defaults:
      run:
        shell: bash
        working-directory: docs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install Dependencies (Linux)
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get install graphviz
      - name: Install Dependencies (Windows)
        if: matrix.platform == 'windows-latest'
        run: choco install graphviz
      - name: Install Dependencies (macOS)
        if: matrix.platform == 'macos-latest'
        run: brew install graphviz
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: npm ci
      - run: npm run build
      - name: Check build status
        run: |
          if [ ! -d "./_site" ]; then
            echo "Build Error"
            exit 1
          fi
      - name: Deploy on push
        # if: ${{ success() && github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy
