name: Deploy RepoSense report

on:
# For active deployment on push to main branch
  push:
    branches:
      - main

steps:
- uses: tlylt/reposense-action@main
  with:
    token: ${{ secrets.GITHUB_TOKEN }} # Required